---
title: "Two-dimensional Spine Plots"
---

### Description

Spine plots are a special cases of mosaic plots, and can be seen as a
generalization of stacked (or highlighted) bar plots. Analogously,
spinograms are an extension of histograms.

This function utilizes [mosaic](https://www.statsmodels.org/stable/generated/statsmodels.graphics.mosaicplot.mosaic.html#statsmodels.graphics.mosaicplot.mosaic) function
from the Python package [statsmodels](https://www.statsmodels.org)
to easily create two-dimensional spine plots based on
[pandas](https://pandas.pydata.org/) DataFrames.

### Usage

<pre><code class='language-python'>spineplot(df, x, y, values=None,<br/>          aggfunc=&#x27;mean&#x27;, labels=None,<br/>          ax=None, colors=None, *args, **kwargs)</code></pre>

### Arguments

<dl class="pyp-list param-list">
  <dt style = "white-space: nowrap; font-family: monospace; vertical-align: top">
   <code id="polarchart.spineplot.spineplot:df">df</code><code class="argument-class">pandas.core.frame.DataFrame</code>
  </dt>
 <dd>A pandas DataFrame.</dd>
  <dt style = "white-space: nowrap; font-family: monospace; vertical-align: top">
   <code id="polarchart.spineplot.spineplot:x">x</code><code class="argument-class">str</code>
  </dt>
 <dd>Name of the variable for the first dimension.</dd>
  <dt style = "white-space: nowrap; font-family: monospace; vertical-align: top">
   <code id="polarchart.spineplot.spineplot:y">y</code><code class="argument-class">str</code>
  </dt>
 <dd>Name of the variable for the second dimension. Must be
categorical or easily convertable to categorical (i.e.,
strings or integers with less than 10 unique values).</dd>
  <dt style = "white-space: nowrap; font-family: monospace; vertical-align: top">
   <code id="polarchart.spineplot.spineplot:values">values</code><code class="argument-class">None, str</code>
  </dt>
 <dd>If `None` (default) absolute/relative counts are calculated
and displayed. The name of an additional column in `df` can be specified which
will be used (in combination with `aggfunc`) to calculate the values visualized.</dd>
  <dt style = "white-space: nowrap; font-family: monospace; vertical-align: top">
   <code id="polarchart.spineplot.spineplot:aggfunc">aggfunc</code><code class="argument-class">str</code>
  </dt>
 <dd>Ignored if `values = None`. If `values` is specified a function
or a string with the name of a numpy function can be specified used for
aggregation. Defaults to `"mean"` (`numpy.mean`).</dd>
  <dt style = "white-space: nowrap; font-family: monospace; vertical-align: top">
   <code id="polarchart.spineplot.spineplot:labels">labels</code><code class="argument-class">None, str</code>
  </dt>
 <dd>Either `None` (default) to suppress labels,
or one of `"absolute"`, `"relative"`, `"percent"`.</dd>
  <dt style = "white-space: nowrap; font-family: monospace; vertical-align: top">
   <code id="polarchart.spineplot.spineplot:ax">ax</code><code class="argument-class">None or matplotlib.axes._axes.Axes</code>
  </dt>
 <dd>If None, a new figure is
initialized. Else the existing axis is taken, manipulated, and populated.</dd>
  <dt style = "white-space: nowrap; font-family: monospace; vertical-align: top">
   <code id="polarchart.spineplot.spineplot:colors">colors</code><code class="argument-class">None or list</code>
  </dt>
 <dd>If `None` (default) a series of grayscale colors
is used. Can be a list of colors which must match the number of
categories in y.</dd>
  <dt style = "white-space: nowrap; font-family: monospace; vertical-align: top">
   <code id="polarchart.spineplot.spineplot:*args">*args</code>
  </dt>
 <dd>Positional arguments; used by other functions interfacing this main
function (`stars()`, ...).</dd>
  <dt style = "white-space: nowrap; font-family: monospace; vertical-align: top">
   <code id="polarchart.spineplot.spineplot:**kwargs">**kwargs</code>
  </dt>
 <dd>Additional keyword arguments, see Details for more information.</dd>
</dl>

### Return

If `ax = None` (no custom axis provided) a list of length two is
returned with (i) the data frame with the categorical variables
used to calculate the spine plot as well as the cross-table
the plot is based on. If a custom axis was provided, the modified
axis is returned.

### Examples

```{python}
#| echo: true
#| warning: true
#| error: true
from numpy import repeat
from pandas import DataFrame, Series, Categorical
from polarchart import spineplot
import matplotlib.pyplot as plt

## Treatment and improvement of patients with rheumatoid arthritis
treatment = Series(repeat([1, 2], [43, 41])).map({1: "placebo", 2: "treated"}) 
improved  = Series(repeat([1, 2, 3, 1, 2, 3], [29, 7, 7, 13, 7, 21])).map({1: "none", 2: "some", 3: "marked"})
df = DataFrame({"treatment": treatment, "improved": improved})
## Convert to categorial data and manually re-order the levels
df.improved = df.improved.astype("category")
df.improved = df.improved.cat.reorder_categories(["marked", "some", "none"])
spineplot(df, x = "treatment", y = "improved",
          title = "Rheumatoid arthritis treatment")

## NASA space shuttle o-ring failures
fail = Series([2, 2, 2, 2, 1, 1, 1, 1, 1, 1, 2, 1,
               2, 1, 1, 1, 1, 2, 1, 1, 1, 1, 1])
fail = fail.map({1: "no", 2: "yes"})
temperature = [53, 57, 58, 63, 66, 67, 67, 67, 68, 69, 70, 70,
               70, 70, 72, 73, 75, 75, 76, 76, 78, 79, 81]
df   = DataFrame({"fail": Series(fail).astype("category"),
                  "temperature": temperature})
df.fail = df.fail.cat.reorder_categories(["yes", "no"])
spineplot(df, "temperature", "fail", figsize = (7, 3))
## Custom figure/axis and customized spine plot
fig, ax = plt.subplots(figsize = (7, 3))
spineplot(df, x = "temperature", y = "fail", ax = ax,
          title = "NASA space shuttle o-ring failures",
          colors = ["#21CCAD", "#F99BAE"])
plt.show()

## Student Admissions at UC Berkeley
UCBA = DataFrame({"Admit":  Categorical(repeat(["Admitted", "Rejected"], [12, 12])),
                  "Gender": Categorical(repeat(["Male", "Female", "Male", "Female"], [6, 6, 6, 6])),
                  "Dept":   Categorical(repeat([["A", "B", "C", "D", "E", "F"]], 4, axis = 0).flatten()),
                  "Freq":   [512, 353, 120, 138, 53, 22, 89, 17, 202, 131, 94, 24,
                             313, 207, 205, 279, 138, 351, 19, 8, 391, 244, 299, 317]})
fig, axs = plt.subplots(2, 1, figsize = (6, 8))
spineplot(UCBA, x = "Dept", y = "Gender", ax = axs[0])
spineplot(UCBA, x = "Dept", y = "Gender", values = "Freq", labels = "absolute",
          digits = 1, ax = axs[1], fontcolor = "steelblue")
plt.show()
```



